spring:
  application:
    name: InvoiceWebService
  # ==============================================================
  # = DBMS PostgreSQL Parameters
  # ==============================================================
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: root
    platform: postgres
    url: jdbc:postgresql://localhost:5432/invoices_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

